language: node_js
node_js:
  - 0.10
  - node
  - iojs
before_script:
  - npm install -d
  - npm install grunt-cli
  - npm install codeclimate-test-reporter
cache:
  directories:
    - node_modules
branches:
  only:
    - master
